services:
  ros2_camera_processor:
    image: camera-processor:jazzy
    container_name: camera_processor_ws
    volumes:
      - .:/workspaces/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1
      - OPENCV_VIDEOIO_PRIORITY_GSTREAMER=0
    # devices:
    #   - "/dev/video0:/dev/video0"
    #group_add:
    #  - video
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    command: /bin/bash